import { Restaurant, Category, Product, DeliveryZone, Role } from '../types/index.ts';

export const INITIAL_RESTAURANT: Restaurant = {
  id: 'rest-dz-001',
  name: 'مطعم ومشاوي البهجة العاصمي',
  slug: 'elbahdja-alger',
  description: 'نقدم لكم أشهى المشاوي على الفحم، والشاورما الجزائرية الأصيلة بخبز الصاج، والطاكوس العاصمي والبرغر الطازج، وبيتزا الفرن التقليدي مع خدمة التوصيل السريع والدفع عند الاستلام.',
  logoUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=240&h=240&q=80',
  coverImageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1600&q=80',
  phone: '0550 12 34 56',
  email: 'contact@elbahdja.dz',
  
  // العنوان الجزائري
  wilaya: 'الجزائر العاصمة (16)',
  commune: 'سيدي امحمد',
  address: '14 شارع ديدوش مراد، قرب ساحة أول ماي، سيدي امحمد، الجزائر العاصمة',
  
  currency: 'دج',
  currencyCode: 'DZD',
  isOpen: true,
  openingHours: 'يومياً من 11:30 صباحاً إلى 23:30 ليلاً بتوقيت الجزائر',
  timezone: 'Africa/Algiers',
  
  defaultDeliveryFee: 300, // 300 دج
  minOrderAmount: 800,     // 800 دج
  defaultCourierFeePerOrder: 100, // 100 دج أجرة التوصيل الافتراضية لكل طلب للمندوب
  
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const INITIAL_DELIVERY_ZONES: DeliveryZone[] = [
  {
    id: 'zone-01',
    restaurantId: 'rest-dz-001',
    wilaya: 'الجزائر العاصمة',
    wilayaCode: '16',
    commune: 'سيدي امحمد / الجزائر الوسطى',
    deliveryFee: 200, // 200 دج
    estimatedMinutes: 30,
    minOrderAmount: 600,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'zone-02',
    restaurantId: 'rest-dz-001',
    wilaya: 'الجزائر العاصمة',
    wilayaCode: '16',
    commune: 'القصبة / باب الواد',
    deliveryFee: 250, // 250 دج
    estimatedMinutes: 35,
    minOrderAmount: 600,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'zone-03',
    restaurantId: 'rest-dz-001',
    wilaya: 'الجزائر العاصمة',
    wilayaCode: '16',
    commune: 'المرادية / المدنية / بلوزداد',
    deliveryFee: 250, // 250 دج
    estimatedMinutes: 35,
    minOrderAmount: 700,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'zone-04',
    restaurantId: 'rest-dz-001',
    wilaya: 'الجزائر العاصمة',
    wilayaCode: '16',
    commune: 'حيدرة / بن عكنون / الأبيار',
    deliveryFee: 300, // 300 دج
    estimatedMinutes: 40,
    minOrderAmount: 800,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'zone-05',
    restaurantId: 'rest-dz-001',
    wilaya: 'الجزائر العاصمة',
    wilayaCode: '16',
    commune: 'القبة / بئر خادم / بئر مراد رايس',
    deliveryFee: 350, // 350 دج
    estimatedMinutes: 45,
    minOrderAmount: 800,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'zone-06',
    restaurantId: 'rest-dz-001',
    wilaya: 'الجزائر العاصمة',
    wilayaCode: '16',
    commune: 'باب الزوار / الحراش / المحمدية',
    deliveryFee: 400, // 400 دج
    estimatedMinutes: 50,
    minOrderAmount: 1000,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'zone-07',
    restaurantId: 'rest-dz-001',
    wilaya: 'الجزائر العاصمة',
    wilayaCode: '16',
    commune: 'دالي براهيم / الشراقة',
    deliveryFee: 450, // 450 دج
    estimatedMinutes: 50,
    minOrderAmount: 1000,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    restaurantId: 'rest-dz-001',
    name: 'شاورما وسندويتشات جزائرية',
    description: 'شاورما على أصولها بالصلصة الجزائرية الحارة والبطاطا المقرمشة',
    icon: '🌯',
    imageUrl: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=600&q=80',
    displayOrder: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-2',
    restaurantId: 'rest-dz-001',
    name: 'مشاوي وأطباق على الفحم',
    description: 'لحم خروف محلي، مرقاز عاصمي حار، وكفتة مشوية على الجمر',
    icon: '🥩',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=600&q=80',
    displayOrder: 2,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-3',
    restaurantId: 'rest-dz-001',
    name: 'طاكوس وبرغر الشيف',
    description: 'طاكوس جزائري بصلصة الجبن الذائبة وبرغر اللحم الطازج',
    icon: '🍔',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
    displayOrder: 3,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-4',
    restaurantId: 'rest-dz-001',
    name: 'بيتزا الفرن الإيطالي',
    description: 'بيتزا كاري ونابولي بجبن الموتزاريلا والصلصة المعطرة',
    icon: '🍕',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
    displayOrder: 4,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-5',
    restaurantId: 'rest-dz-001',
    name: 'مقبلات وسلطات وفريت',
    description: 'بطاطا مقلية طازجة، سلطة مشوية، حميس حار، وصلصات منزلية',
    icon: '🍟',
    imageUrl: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=600&q=80',
    displayOrder: 5,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cat-6',
    restaurantId: 'rest-dz-001',
    name: 'مشروبات وحلويات جزائرية',
    description: 'مشروبات حمود بوعلام المنعشة، عصائر طبيعية وقلب اللوز العاصمي',
    icon: '🥤',
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
    displayOrder: 6,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // 1. شاورما وسندويتشات جزائرية
  {
    id: 'prod-dz-01',
    restaurantId: 'rest-dz-001',
    categoryId: 'cat-1',
    name: 'سندويتش شاورما دجاج جامبو بالخبز السوري',
    description: 'قطع شاورما دجاج متبلة ببهارات الشيف الخاصة مع بطاطا مقلية، صلصة الثومية المنزلية، صلصة حارة جزائرية ومخلل الخيار المقرمش.',
    price: 450, // 450 دج
    imageUrl: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    displayOrder: 1,
    preparationTimeMinutes: 12,
    calories: 620,
    tags: 'الأكثر طلباً, شاورما دجاج, صلصة حارة',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-dz-02',
    restaurantId: 'rest-dz-001',
    categoryId: 'cat-1',
    name: 'صحن شاورما عربي دجاج عائلي',
    description: 'لفائف شاورما محمرة ومقطعة تقدم مع حصة وافرة من البطاطا المقلية، صحن ثومية، صلصة هريسة منزلية وزيتون مرقد محلي.',
    price: 750, // 750 دج
    imageUrl: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    displayOrder: 2,
    preparationTimeMinutes: 15,
    calories: 840,
    tags: 'وجبة متكاملة, عائلي, دجاج محمر',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-dz-03',
    restaurantId: 'rest-dz-001',
    categoryId: 'cat-1',
    name: 'سندويتش شاورما لحم عجل بلدي بالبصل والسماق',
    description: 'لحم عجل طازج متبل بالبهارات الشرقية مع صلصة الطحينة والبقدونس وشرائح البصل بالسماق في خبز طازج دافئ.',
    price: 600, // 600 دج
    imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    displayOrder: 3,
    preparationTimeMinutes: 15,
    calories: 680,
    tags: 'لحم بلدي, نكهة خاصة',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 2. مشاوي وأطباق على الفحم
  {
    id: 'prod-dz-04',
    restaurantId: 'rest-dz-001',
    categoryId: 'cat-2',
    name: 'طبق ميكس مشاوي البهجة الملكي على الفحم',
    description: 'تشكيلة مميزة تضم: سيخ كفتة لحم غنم مشوي، سيخ قطبان لحم خروف طري، مرقاز جزائري حار على الفحم، يقدم مع بطاطا مقلية وسلطة وخبر الدار.',
    price: 1200, // 1,200 دج
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    displayOrder: 4,
    preparationTimeMinutes: 25,
    calories: 920,
    tags: 'الأكثر طلباً ⭐, مشاوي فحم, لحم محلي 100%',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-dz-05',
    restaurantId: 'rest-dz-001',
    categoryId: 'cat-2',
    name: 'طبق مرقاز جزائري بلدي حار مشوي',
    description: 'أصابع مرقاز بلدي محضر يدوياً من لحم الخروف المتبل بالهريسة والكمون والثوم، مشوي على الجمر مع الخضار المشوية.',
    price: 850, // 850 دج
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    displayOrder: 5,
    preparationTimeMinutes: 20,
    calories: 780,
    tags: 'مرقاز حار 🔥, تقليدي عاصمي',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-dz-06',
    restaurantId: 'rest-dz-001',
    categoryId: 'cat-2',
    name: 'طبق أسياخ كفتة لحم خروف محلي متبلة',
    description: '3 أسياخ من كفتة لحم الخروف المحلي المفروم مع البصل والنعناع والتوابل العاصمية، تقدم مع حميس حار وخبز تقليدي.',
    price: 900, // 900 دج
    imageUrl: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    displayOrder: 6,
    preparationTimeMinutes: 20,
    calories: 750,
    tags: 'كفتة مشوية, بهارات جزائرية',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 3. طاكوس وبرغر الشيف
  {
    id: 'prod-dz-07',
    restaurantId: 'rest-dz-001',
    categoryId: 'cat-3',
    name: 'طاكوس جزائري دبل ماكسي بلحم مفروم ودجاج',
    description: 'طاكوس محشو باللحم المفروم وقطع الدجاج المقرمشة، بطاطا مقلية بالداخل، صلصة الجبن المنزلية الساخنة وصلصة ألجيريان حارة.',
    price: 650, // 650 دج
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    displayOrder: 7,
    preparationTimeMinutes: 18,
    calories: 890,
    tags: 'طاكوس جزائري, صلصة جبن, دبل لحم',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-dz-08',
    restaurantId: 'rest-dz-001',
    categoryId: 'cat-3',
    name: 'برغر البهجة سبيسيال دبل تشيز',
    description: 'شريحتان من لحم العجل الطازج (180جم)، شيدر أحمر ذائب، بصل مكرمل، بيض مقلي، خس، وصلصة برغر منزلية في خبز بريوش طازج.',
    price: 700, // 700 دج
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    displayOrder: 8,
    preparationTimeMinutes: 18,
    calories: 820,
    tags: 'برغر لحم طازج, شيدر ذائب',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-dz-09',
    restaurantId: 'rest-dz-001',
    categoryId: 'cat-3',
    name: 'برغر كرسبي الدجاج الحار المقرمش',
    description: 'صدر دجاج مقلي ومتبل بخلطة مقرمشة حارة، جبنة سويسرية، سلطة كولسلو، صوص حار ومخلل.',
    price: 550, // 550 دج
    imageUrl: 'https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    displayOrder: 9,
    preparationTimeMinutes: 15,
    calories: 710,
    tags: 'كرسبي دجاج, مقرمش وحار',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 4. بيتزا الفرن الإيطالي والتقليدي
  {
    id: 'prod-dz-10',
    restaurantId: 'rest-dz-001',
    categoryId: 'cat-4',
    name: 'بيتزا كاري جزائرية تقليدية بالفرن',
    description: 'عجينة بيتزا جزائرية هشة، صلصة طماطم معطرة بالزعتر البري والثوم، جبن غرويير، زيتون أسود جزائري ورشة زيت زيتون بكر.',
    price: 500, // 500 دج
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    displayOrder: 10,
    preparationTimeMinutes: 15,
    calories: 760,
    tags: 'بيتزا تقليدية, زيتون أسود',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-dz-11',
    restaurantId: 'rest-dz-001',
    categoryId: 'cat-4',
    name: 'بيتزا سوبريم فواكه البحر بجبن الموتزاريلا',
    description: 'صلصة طماطم سان مارزانو، جمبري طازج، حبار، جبنة موتزاريلا طبيعية، بقدونس وزيت زيتون معطر بالثوم.',
    price: 950, // 950 دج
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    displayOrder: 11,
    preparationTimeMinutes: 18,
    calories: 830,
    tags: 'فواكه البحر, موتزاريلا إيطالية',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 5. مقبلات وسلطات وفريت
  {
    id: 'prod-dz-12',
    restaurantId: 'rest-dz-001',
    categoryId: 'cat-5',
    name: 'صحن فريت أومليت جزائرية بالجبن الذائب',
    description: 'أصابع بطاطا مقلية طازجة ممزوجة ببيض الدجاج البلدي وجبن الشيدر مع رشة بقدونس وكمون وصلصة الهريسة.',
    price: 350, // 350 دج
    imageUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    displayOrder: 12,
    preparationTimeMinutes: 10,
    calories: 520,
    tags: 'فريت أومليت, شعبي جزائري',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-dz-13',
    restaurantId: 'rest-dz-001',
    categoryId: 'cat-5',
    name: 'سلطة حميس عاصمي حار مشوي بزيت الزيتون',
    description: 'فلفل حلو وحار مشوي على النار مهروس مع الطماطم والثوم وزيت الزيتون القبائلي البكر، يزين بقطع البيض المسلوق والزيتون.',
    price: 300, // 300 دج
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    displayOrder: 13,
    preparationTimeMinutes: 8,
    calories: 280,
    tags: 'حميس حار, زيت زيتون بكر',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 6. مشروبات وحلويات جزائرية
  {
    id: 'prod-dz-14',
    restaurantId: 'rest-dz-001',
    categoryId: 'cat-6',
    name: 'مشروب حمود بوعلام سيليكتو زجاج بارد',
    description: 'المشروب الغازي الجزائري الشهير بنكهة الكراميل المنعشة، يقدم بارداً ومثلجاً.',
    price: 150, // 150 دج
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: false,
    displayOrder: 14,
    preparationTimeMinutes: 3,
    calories: 140,
    tags: 'حمود بوعلام, مشروب وطني بارد',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-dz-15',
    restaurantId: 'rest-dz-001',
    categoryId: 'cat-6',
    name: 'قطعة قلب اللوز العاصمي التقليدي المعسل',
    description: 'حلوى قلب اللوز الجزائرية الأصيلة بالسميد واللوز المطحون، مسقية بالشاربات المعطرة بماء الزهر ومزينة بحبة لوز.',
    price: 200, // 200 دج
    imageUrl: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?auto=format&fit=crop&w=800&q=80',
    isAvailable: true,
    isFeatured: true,
    displayOrder: 15,
    preparationTimeMinutes: 5,
    calories: 420,
    tags: 'قلب اللوز, ماء زهر, معسل',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_USERS_RAW = [
  {
    id: 'usr-admin-dz-01',
    restaurantId: 'rest-dz-001',
    name: 'أمين بن علي',
    email: 'admin@elbahdja.dz',
    passwordPlain: 'Admin@123456',
    phone: '0550123456',
    role: 'ADMIN' as Role,
    isActive: true,
  },
  {
    id: 'usr-mgr-dz-01',
    restaurantId: 'rest-dz-001',
    name: 'ياسمين بلقاسم',
    email: 'manager@elbahdja.dz',
    passwordPlain: 'Manager@123456',
    phone: '0661234567',
    role: 'MANAGER' as Role,
    isActive: true,
  },
  {
    id: 'usr-del-dz-01',
    restaurantId: 'rest-dz-001',
    name: 'كريم دراجي',
    email: 'delivery@elbahdja.dz',
    passwordPlain: 'Delivery@123456',
    phone: '0770345678',
    role: 'DELIVERY' as Role,
    isActive: true,
  },
  {
    id: 'usr-del-dz-02',
    restaurantId: 'rest-dz-001',
    name: 'سمير بوزيد',
    email: 'samir.delivery@elbahdja.dz',
    passwordPlain: 'Delivery@123456',
    phone: '0552789123',
    role: 'DELIVERY' as Role,
    isActive: true,
  },
];

export const INITIAL_DELIVERY_PEOPLE = [
  {
    id: 'dp-01',
    restaurantId: 'rest-dz-001',
    userId: 'usr-del-dz-01',
    name: 'كريم دراجي',
    phone: '0770345678',
    email: 'delivery@elbahdja.dz',
    isActive: true,
    isAvailable: true,
    deliveryFeePerOrder: 100, // 100 دج لكل طلب
    vehicleType: 'دراجة نارية (Moto SYM)',
    vehiclePlateNumber: '16-45892-001',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'dp-02',
    restaurantId: 'rest-dz-001',
    userId: 'usr-del-dz-02',
    name: 'سمير بوزيد',
    phone: '0552789123',
    email: 'samir.delivery@elbahdja.dz',
    isActive: true,
    isAvailable: true,
    deliveryFeePerOrder: 100, // 100 دج لكل طلب
    vehicleType: 'سيارة (Renault Clio)',
    vehiclePlateNumber: '16-78214-002',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
